global:
  scrape_interval: 5s # Short interval for fast monitoring updates (ideal for review checking)
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'heart-disease-api-monitoring'
    metrics_path: '/metrics'
    static_configs:
      # Use 'localhost:8000' if running Prometheus locally.
      # Use 'host.docker.internal:8000' if running Prometheus in Docker.
      - targets: ['localhost:8000', 'host.docker.internal:8000']
