name: Automated Preprocessing Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'dataset_raw/heart_disease.csv'
      - 'preprocessing/automate_Kevin_Adiputra.py'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
  contents: write # Essential to allow the workflow to commit changes back to the repo

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # Caches pip dependencies for faster runs

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_Kevin_Adiputra.py

    - name: Commit and Push Changes
      run: |
        git config --local user.email "kevinadiputra66@gmail.com"
        git config --local user.name "Kevinadiputra"
        git add preprocessing/dataset_preprocessed/ preprocessing/dataset_preprocessing/
        git commit -m "update hasil preprocessing data" || echo "No changes to commit"
        git push
